apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - cronjob.yaml
  - serviceaccount.yaml
  - pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/component: snapshot
